# MOSPCUDA Makefile
#
#   make                      build bin/main (sm_86, host -O3, -lineinfo)
#   make CUDA_ARCH=sm_80      build for another GPU architecture
#   make OPT=                 reproduce the original flags (host code at -O0)
#   make NVCC=/path/to/nvcc   use a specific CUDA toolkit
NVCC      ?= nvcc
CUDA_ARCH ?= sm_86
OPT       ?= -O3
CXXFLAGS  := -std=c++17 -Iheaders
NVFLAGS   := --extended-lambda -arch=$(CUDA_ARCH) $(OPT) -lineinfo
DEPFLAGS  := -MMD -MP
SRCDIR    := src
BINDIR    := bin
BUILDDIR  := build

APP      := $(BINDIR)/main

# Base sources (shared by all targets)
BASE_SRCS := $(SRCDIR)/generateGraph.cu $(SRCDIR)/generateGraphCSR.cu $(SRCDIR)/generateChangedEdges.cu $(SRCDIR)/updateGraphCSR.cu $(SRCDIR)/generateTestCases.cu $(SRCDIR)/Dijkstra.cu $(SRCDIR)/read.cu

# Main application (includes sequential SOSP update)
MAIN_SRCS := $(SRCDIR)/main.cu $(BASE_SRCS) $(SRCDIR)/sequentialSOSPUpdate.cu $(SRCDIR)/parallelSOSPUpdate.cu $(SRCDIR)/parallelCombinedGraph.cu
MAIN_OBJS := $(MAIN_SRCS:$(SRCDIR)/%.cu=$(BUILDDIR)/%.o)

# Sequential stress test
STRESS_SRCS := $(SRCDIR)/stressTest.cu $(BASE_SRCS) $(SRCDIR)/sequentialSOSPUpdate.cu
STRESS_OBJS := $(STRESS_SRCS:$(SRCDIR)/%.cu=$(BUILDDIR)/%.o)

# Parallel stress test (CUDA)
PARALLEL_STRESS_SRCS := $(SRCDIR)/parallelStressTest.cu $(BASE_SRCS) $(SRCDIR)/parallelSOSPUpdate.cu $(SRCDIR)/sequentialSOSPUpdate.cu
PARALLEL_STRESS_OBJS := $(PARALLEL_STRESS_SRCS:$(SRCDIR)/%.cu=$(BUILDDIR)/%.o)

.PHONY: all clean run stressTest parallelStressTest

all: $(APP)

$(BINDIR) $(BUILDDIR):
	@mkdir -p $@

# --- Main application ---
$(APP): $(MAIN_OBJS) | $(BINDIR)
	$(NVCC) $(CXXFLAGS) $(NVFLAGS) -o $@ $^

$(BUILDDIR)/%.o: $(SRCDIR)/%.cu | $(BUILDDIR)
	$(NVCC) $(CXXFLAGS) $(NVFLAGS) $(DEPFLAGS) -c -o $@ $<

# --- Sequential stress test ---
stressTest: $(BINDIR)/stressTest

$(BINDIR)/stressTest: $(STRESS_OBJS) | $(BINDIR)
	$(NVCC) $(CXXFLAGS) $(NVFLAGS) -o $@ $^

# --- Parallel stress test (CUDA) ---
parallelStressTest: $(BINDIR)/parallelStressTest

$(BINDIR)/parallelStressTest: $(PARALLEL_STRESS_OBJS) | $(BINDIR)
	$(NVCC) $(CXXFLAGS) $(NVFLAGS) -o $@ $^

clean:
	rm -rf $(BINDIR) $(BUILDDIR)

run: $(APP)
	./$(APP)

# Header dependencies generated by -MMD (rebuild objects when a .cuh changes)
-include $(wildcard $(BUILDDIR)/*.d)
